#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/actiondialog.ui on Sun Oct 18 16:04:37 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ActionDialog(object):
    def setupUi(self, ActionDialog):
        ActionDialog.setObjectName("ActionDialog")
        ActionDialog.resize(178, 52)
        self.gridLayout = QtGui.QGridLayout(ActionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.actionSelectLabel = QtGui.QLabel(ActionDialog)
        self.actionSelectLabel.setObjectName("actionSelectLabel")
        self.gridLayout.addWidget(self.actionSelectLabel, 0, 0, 1, 1)
        self.actionSelectComboBox = KComboBox(ActionDialog)
        self.actionSelectComboBox.setObjectName("actionSelectComboBox")
        self.actionSelectComboBox.addItem("")
        self.actionSelectComboBox.addItem("")
        self.gridLayout.addWidget(self.actionSelectComboBox, 0, 1, 1, 1)
        self.actionSelectLabel.setBuddy(self.actionSelectComboBox)

        self.retranslateUi(ActionDialog)
        QtCore.QMetaObject.connectSlotsByName(ActionDialog)

    def retranslateUi(self, ActionDialog):
        self.actionSelectLabel.setText(kdecore.i18n("Actions "))
        self.actionSelectComboBox.setItemText(0, kdecore.i18n("Display image"))
        self.actionSelectComboBox.setItemText(1, kdecore.i18n("Download image"))

from PyKDE4.kdeui import KComboBox
