#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/fetchdialog.ui on Sun Oct 11 18:24:19 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_FetchDialog(object):
    def setupUi(self, FetchDialog):
        FetchDialog.setObjectName("FetchDialog")
        FetchDialog.resize(352, 62)
        self.formLayout = QtGui.QFormLayout(FetchDialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(FetchDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(FetchDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tagLineEdit = KLineEdit(FetchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagLineEdit.sizePolicy().hasHeightForWidth())
        self.tagLineEdit.setSizePolicy(sizePolicy)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tagLineEdit)
        self.postSpinBox = KIntSpinBox(FetchDialog)
        self.postSpinBox.setMinimum(1)
        self.postSpinBox.setMaximum(100)
        self.postSpinBox.setObjectName("postSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.postSpinBox)

        self.retranslateUi(FetchDialog)
        QtCore.QMetaObject.connectSlotsByName(FetchDialog)

    def retranslateUi(self, FetchDialog):
        self.label.setText(kdecore.i18n("Posts to retrieve"))
        self.label_2.setText(kdecore.i18n("Tags to include"))
        self.tagLineEdit.setToolTip(kdecore.i18n("Tags to include in search (optional)"))
        self.tagLineEdit.setClickMessage(kdecore.i18n("Tags, comma separated"))
        self.postSpinBox.setToolTip(kdecore.i18n("Number of posts to retrieve (max 100)"))

from PyKDE4.kdeui import KLineEdit, KIntSpinBox
