#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/generalpage.ui on Tue Oct 20 22:23:15 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_GeneralPage(object):
    def setupUi(self, GeneralPage):
        GeneralPage.setObjectName("GeneralPage")
        GeneralPage.resize(501, 487)
        self.verticalLayout = QtGui.QVBoxLayout(GeneralPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kcfg_danbooruUrls = KEditListBox(GeneralPage)
        self.kcfg_danbooruUrls.setFlat(True)
        self.kcfg_danbooruUrls.setCheckable(False)
        self.kcfg_danbooruUrls.setButtons(kdeui.KEditListBox.Add|kdeui.KEditListBox.Remove)
        self.kcfg_danbooruUrls.setObjectName("kcfg_danbooruUrls")
        self.verticalLayout.addWidget(self.kcfg_danbooruUrls)
        self.groupBox = QtGui.QGroupBox(GeneralPage)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.kfcfg_thumbnailMaxRetrieve = KIntNumInput(self.groupBox)
        self.kfcfg_thumbnailMaxRetrieve.setMinimum(1)
        self.kfcfg_thumbnailMaxRetrieve.setMaximum(100)
        self.kfcfg_thumbnailMaxRetrieve.setObjectName("kfcfg_thumbnailMaxRetrieve")
        self.gridLayout.addWidget(self.kfcfg_thumbnailMaxRetrieve, 0, 1, 1, 1)
        self.thumbnalLabel = QtGui.QLabel(self.groupBox)
        self.thumbnalLabel.setObjectName("thumbnalLabel")
        self.gridLayout.addWidget(self.thumbnalLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(131, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(GeneralPage)
        QtCore.QMetaObject.connectSlotsByName(GeneralPage)

    def retranslateUi(self, GeneralPage):
        self.kcfg_danbooruUrls.setTitle(kdecore.i18n("Danbooru URLs"))
        self.groupBox.setTitle(kdecore.i18n("General settings"))
        self.thumbnalLabel.setText(kdecore.i18n("Default number of thumbnails to retrieve"))

from PyKDE4.kdeui import KIntNumInput, KEditListBox
