#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/nepomukpage.ui on Fri Oct 23 21:29:41 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_NepomukPage(object):
    def setupUi(self, NepomukPage):
        NepomukPage.setObjectName("NepomukPage")
        NepomukPage.resize(402, 287)
        self.verticalLayout = QtGui.QVBoxLayout(NepomukPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kcfg_nepomukEnabled = QtGui.QCheckBox(NepomukPage)
        self.kcfg_nepomukEnabled.setEnabled(True)
        self.kcfg_nepomukEnabled.setObjectName("kcfg_nepomukEnabled")
        self.verticalLayout.addWidget(self.kcfg_nepomukEnabled)
        self.kcfg_tagBlacklist = KEditListBox(NepomukPage)
        self.kcfg_tagBlacklist.setEnabled(False)
        self.kcfg_tagBlacklist.setFlat(True)
        self.kcfg_tagBlacklist.setCheckable(False)
        self.kcfg_tagBlacklist.setButtons(KEditListBox.Button(
            KEditListBox.Add|KEditListBox.Remove))
        self.kcfg_tagBlacklist.setObjectName("kcfg_tagBlacklist")
        self.verticalLayout.addWidget(self.kcfg_tagBlacklist)

        self.retranslateUi(NepomukPage)
        QtCore.QMetaObject.connectSlotsByName(NepomukPage)

    def retranslateUi(self, NepomukPage):
        self.kcfg_nepomukEnabled.setText(kdecore.i18n("Enable Nepomuk tagging"))
        self.kcfg_tagBlacklist.setTitle(kdecore.i18n("Tag blacklist"))

from PyKDE4.kdeui import KEditListBox
