#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/connectwidget.ui on Wed Dec 26 10:19:33 2012
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_connectForm(object):
    def setupUi(self, connectForm):
        connectForm.setObjectName(_fromUtf8("connectForm"))
        connectForm.resize(655, 33)
        connectForm.setWindowTitle(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(connectForm)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.closeButton = KPushButton(connectForm)
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.urlLabel = QtGui.QLabel(connectForm)
        self.urlLabel.setObjectName(_fromUtf8("urlLabel"))
        self.horizontalLayout.addWidget(self.urlLabel)
        self.danbooruUrlComboBox = KComboBox(connectForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.danbooruUrlComboBox.sizePolicy().hasHeightForWidth())
        self.danbooruUrlComboBox.setSizePolicy(sizePolicy)
        self.danbooruUrlComboBox.setEditable(False)
        self.danbooruUrlComboBox.setObjectName(_fromUtf8("danbooruUrlComboBox"))
        self.horizontalLayout.addWidget(self.danbooruUrlComboBox)
        self.userLabel = QtGui.QLabel(connectForm)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.horizontalLayout.addWidget(self.userLabel)
        self.userLineEdit = KLineEdit(connectForm)
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.horizontalLayout.addWidget(self.userLineEdit)
        self.passwordLabel = QtGui.QLabel(connectForm)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.horizontalLayout.addWidget(self.passwordLabel)
        self.passwdLineEdit = KLineEdit(connectForm)
        self.passwdLineEdit.setPasswordMode(True)
        self.passwdLineEdit.setObjectName(_fromUtf8("passwdLineEdit"))
        self.horizontalLayout.addWidget(self.passwdLineEdit)
        self.buttonBox = KDialogButtonBox(connectForm)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(connectForm)
        QtCore.QMetaObject.connectSlotsByName(connectForm)

    def retranslateUi(self, connectForm):
        self.urlLabel.setText(kdecore.i18n(_fromUtf8("Danbooru URL")))
        self.userLabel.setText(kdecore.i18n(_fromUtf8("Username")))
        self.userLineEdit.setClickMessage(kdecore.i18n(_fromUtf8("Danbooru username (optional)")))
        self.passwordLabel.setText(kdecore.i18n(_fromUtf8("Password")))
        self.passwdLineEdit.setClickMessage(kdecore.i18n(_fromUtf8("Danbooru password (optional)")))

from PyKDE4.kdeui import KLineEdit, KDialogButtonBox, KPushButton, KComboBox
