#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/connectwidget.ui on Sat Sep 22 15:27:20 2012
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_connectForm(object):
    def setupUi(self, connectForm):
        connectForm.setObjectName(_fromUtf8("connectForm"))
        connectForm.resize(270, 114)
        connectForm.setWindowTitle(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(connectForm)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.closeButton = KPushButton(connectForm)
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout.addWidget(self.closeButton, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.urlLabel = QtGui.QLabel(connectForm)
        self.urlLabel.setObjectName(_fromUtf8("urlLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.urlLabel)
        self.danbooruUrlComboBox = KComboBox(connectForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.danbooruUrlComboBox.sizePolicy().hasHeightForWidth())
        self.danbooruUrlComboBox.setSizePolicy(sizePolicy)
        self.danbooruUrlComboBox.setEditable(False)
        self.danbooruUrlComboBox.setObjectName(_fromUtf8("danbooruUrlComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.danbooruUrlComboBox)
        self.userLabel = QtGui.QLabel(connectForm)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.userLabel)
        self.userLineEdit = KLineEdit(connectForm)
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.userLineEdit)
        self.passwordLabel = QtGui.QLabel(connectForm)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.passwordLabel)
        self.passwdLineEdit = KLineEdit(connectForm)
        self.passwdLineEdit.setPasswordMode(True)
        self.passwdLineEdit.setObjectName(_fromUtf8("passwdLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.passwdLineEdit)
        self.buttonBox = KDialogButtonBox(connectForm)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 2, 1)

        self.retranslateUi(connectForm)
        QtCore.QMetaObject.connectSlotsByName(connectForm)

    def retranslateUi(self, connectForm):
        self.urlLabel.setText(kdecore.i18n(_fromUtf8("Danbooru URL")))
        self.userLabel.setText(kdecore.i18n(_fromUtf8("Username")))
        self.userLineEdit.setClickMessage(kdecore.i18n(_fromUtf8("Danbooru username (optional)")))
        self.passwordLabel.setText(kdecore.i18n(_fromUtf8("Password")))
        self.passwdLineEdit.setClickMessage(kdecore.i18n(_fromUtf8("Danbooru password (optional)")))

from PyKDE4.kdeui import KLineEdit, KDialogButtonBox, KPushButton, KComboBox
