#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/fetchdialog.ui on Wed Nov  4 00:28:34 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_FetchDialog(object):
    def setupUi(self, FetchDialog):
        FetchDialog.setObjectName("FetchDialog")
        FetchDialog.resize(259, 91)
        self.formLayout = QtGui.QFormLayout(FetchDialog)
        self.formLayout.setObjectName("formLayout")
        self.postLabel = QtGui.QLabel(FetchDialog)
        self.postLabel.setObjectName("postLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.postLabel)
        self.postSpinBox = KIntSpinBox(FetchDialog)
        self.postSpinBox.setMinimum(1)
        self.postSpinBox.setMaximum(100)
        self.postSpinBox.setObjectName("postSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.postSpinBox)
        self.tagLabel = QtGui.QLabel(FetchDialog)
        self.tagLabel.setObjectName("tagLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.tagLabel)
        self.tagLineEdit = KLineEdit(FetchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagLineEdit.sizePolicy().hasHeightForWidth())
        self.tagLineEdit.setSizePolicy(sizePolicy)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tagLineEdit)
        self.ratingLabel = QtGui.QLabel(FetchDialog)
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ratingLabel)
        self.ratingComboBox = KComboBox(FetchDialog)
        self.ratingComboBox.setObjectName("ratingComboBox")
        self.ratingComboBox.addItem("")
        self.ratingComboBox.addItem("")
        self.ratingComboBox.addItem("")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ratingComboBox)

        self.retranslateUi(FetchDialog)
        QtCore.QMetaObject.connectSlotsByName(FetchDialog)

    def retranslateUi(self, FetchDialog):
        self.postLabel.setText(kdecore.i18n("Posts to retrieve"))
        self.postSpinBox.setToolTip(kdecore.i18n("Number of posts to retrieve (max 100)"))
        self.postSpinBox.setWhatsThis(kdecore.i18n("The number of posts to retrieve. Notice that Danbooru limits the maximum number of posts to 100."))
        self.tagLabel.setText(kdecore.i18n("Tags to include"))
        self.tagLineEdit.setToolTip(kdecore.i18n("Tags to include in search (optional)"))
        self.tagLineEdit.setWhatsThis(kdecore.i18n("Input here the tags that should be used when looking for posts. Separate them with commas, without spaces."))
        self.tagLineEdit.setClickMessage(kdecore.i18n("Tags, comma separated"))
        self.ratingLabel.setText(kdecore.i18n("Maximum allowed rating"))
        self.ratingComboBox.setWhatsThis(kdecore.i18n("This selects the maximum ratings for the image. \"Safe\" images are intended for all audiences; \"Questionable\" images may contain suggestive but not explicit imagery; \"Explicit\" images contain very explicit content."))
        self.ratingComboBox.setItemText(0, kdecore.i18n("Safe"))
        self.ratingComboBox.setItemText(1, kdecore.i18n("Questionable"))
        self.ratingComboBox.setItemText(2, kdecore.i18n("Explicit"))

from PyKDE4.kdeui import KLineEdit, KIntSpinBox, KComboBox
