#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/fetchdialog.ui on Wed Dec 30 12:56:59 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_FetchDialog(object):
    def setupUi(self, FetchDialog):
        FetchDialog.setObjectName("FetchDialog")
        FetchDialog.resize(218, 183)
        self.formLayout = QtGui.QFormLayout(FetchDialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.postSpinBox = KIntSpinBox(FetchDialog)
        self.postSpinBox.setMinimum(1)
        self.postSpinBox.setMaximum(100)
        self.postSpinBox.setObjectName("postSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.postSpinBox)
        self.tagLineEdit = KLineEdit(FetchDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagLineEdit.sizePolicy().hasHeightForWidth())
        self.tagLineEdit.setSizePolicy(sizePolicy)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tagLineEdit)
        self.tagLabel = QtGui.QLabel(FetchDialog)
        self.tagLabel.setObjectName("tagLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.tagLabel)
        self.postLabel = QtGui.QLabel(FetchDialog)
        self.postLabel.setObjectName("postLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.postLabel)
        self.kbuttongroup = KButtonGroup(FetchDialog)
        self.kbuttongroup.setObjectName("kbuttongroup")
        self.gridLayout = QtGui.QGridLayout(self.kbuttongroup)
        self.gridLayout.setObjectName("gridLayout")
        self.questionableRadioButton = QtGui.QRadioButton(self.kbuttongroup)
        self.questionableRadioButton.setObjectName("questionableRadioButton")
        self.gridLayout.addWidget(self.questionableRadioButton, 1, 0, 1, 1)
        self.explicitRadioButton = QtGui.QRadioButton(self.kbuttongroup)
        self.explicitRadioButton.setObjectName("explicitRadioButton")
        self.gridLayout.addWidget(self.explicitRadioButton, 2, 0, 1, 1)
        self.safeRadioButton = QtGui.QRadioButton(self.kbuttongroup)
        self.safeRadioButton.setObjectName("safeRadioButton")
        self.gridLayout.addWidget(self.safeRadioButton, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.kbuttongroup)

        self.retranslateUi(FetchDialog)
        QtCore.QMetaObject.connectSlotsByName(FetchDialog)

    def retranslateUi(self, FetchDialog):
        self.postSpinBox.setToolTip(kdecore.i18n("Number of posts to retrieve (max 100)"))
        self.postSpinBox.setWhatsThis(kdecore.i18n("The number of posts to retrieve. Notice that Danbooru limits the maximum number of posts to 100."))
        self.tagLineEdit.setToolTip(kdecore.i18n("Tags to include in search (optional)"))
        self.tagLineEdit.setWhatsThis(kdecore.i18n("Input here the tags that should be used when looking for posts. Separate them with commas, without spaces."))
        self.tagLineEdit.setClickMessage(kdecore.i18n("Tags, comma separated"))
        self.tagLabel.setText(kdecore.i18n("Tags:"))
        self.postLabel.setText(kdecore.i18n("Posts to retrieve:"))
        self.kbuttongroup.setTitle(kdecore.i18n("Maximum rating"))
        self.questionableRadioButton.setText(kdecore.i18n("Questionable"))
        self.explicitRadioButton.setText(kdecore.i18n("Explicit"))
        self.safeRadioButton.setText(kdecore.i18n("Safe"))

from PyKDE4.kdeui import KButtonGroup, KLineEdit, KIntSpinBox
