#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/pooldock.ui on Sun Sep 25 15:37:48 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PoolWidget(object):
    def setupUi(self, PoolWidget):
        PoolWidget.setObjectName(_fromUtf8("PoolWidget"))
        PoolWidget.resize(540, 275)
        PoolWidget.setWindowTitle(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(PoolWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fetchButton = KPushButton(PoolWidget)
        self.fetchButton.setText(kdecore.i18n(_fromUtf8("Fetch more pools")))
        self.fetchButton.setObjectName(_fromUtf8("fetchButton"))
        self.gridLayout.addWidget(self.fetchButton, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(430, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.poolTable = QtGui.QTableWidget(PoolWidget)
        self.poolTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.poolTable.setObjectName(_fromUtf8("poolTable"))
        self.poolTable.setColumnCount(4)
        self.poolTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(kdecore.i18n(_fromUtf8("ID")))
        self.poolTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(kdecore.i18n(_fromUtf8("Name")))
        self.poolTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(kdecore.i18n(_fromUtf8("Posts")))
        self.poolTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(kdecore.i18n(_fromUtf8("Description")))
        self.poolTable.setHorizontalHeaderItem(3, item)
        self.poolTable.horizontalHeader().setVisible(True)
        self.poolTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.poolTable, 1, 0, 1, 2)

        self.retranslateUi(PoolWidget)
        QtCore.QMetaObject.connectSlotsByName(PoolWidget)

    def retranslateUi(self, PoolWidget):
        item = self.poolTable.horizontalHeaderItem(0)
        item = self.poolTable.horizontalHeaderItem(1)
        item = self.poolTable.horizontalHeaderItem(2)
        item = self.poolTable.horizontalHeaderItem(3)

from PyKDE4.kdeui import KPushButton
