#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui_src/poolwidget.ui on Tue Jan  5 15:13:09 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_PoolWidget(object):
    def setupUi(self, PoolWidget):
        PoolWidget.setObjectName("PoolWidget")
        PoolWidget.resize(501, 238)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PoolWidget.sizePolicy().hasHeightForWidth())
        PoolWidget.setSizePolicy(sizePolicy)
        PoolWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtGui.QVBoxLayout(PoolWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.poolDataTable = QtGui.QTableWidget(PoolWidget)
        self.poolDataTable.setAlternatingRowColors(False)
        self.poolDataTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.poolDataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.poolDataTable.setObjectName("poolDataTable")
        self.poolDataTable.setColumnCount(3)
        self.poolDataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.poolDataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.poolDataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.poolDataTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.poolDataTable)

        self.retranslateUi(PoolWidget)
        QtCore.QMetaObject.connectSlotsByName(PoolWidget)

    def retranslateUi(self, PoolWidget):
        self.poolDataTable.horizontalHeaderItem(0).setText(kdecore.i18n("ID"))
        self.poolDataTable.horizontalHeaderItem(1).setText(kdecore.i18n("Name"))
        self.poolDataTable.horizontalHeaderItem(2).setText(kdecore.i18n("Posts"))

