#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from /home/lb/Coding/pykde4/danbooru/danbooru/ui_src/thumbnailarea.ui on Sun Apr 18 15:28:20 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ThumbnailArea(object):
    def setupUi(self, ThumbnailArea):
        ThumbnailArea.setObjectName("ThumbnailArea")
        ThumbnailArea.resize(570, 502)
        ThumbnailArea.setWindowTitle("")
        self.gridLayout = QtGui.QGridLayout(ThumbnailArea)
        self.gridLayout.setObjectName("gridLayout")
        self.thumbnailTabWidget = KTabWidget(ThumbnailArea)
        self.thumbnailTabWidget.setObjectName("thumbnailTabWidget")
        self.gridLayout.addWidget(self.thumbnailTabWidget, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(370, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.nextPageButton = KPushButton(ThumbnailArea)
        self.nextPageButton.setObjectName("nextPageButton")
        self.gridLayout.addWidget(self.nextPageButton, 2, 1, 1, 1)
        self.tagList = QtGui.QListWidget(ThumbnailArea)
        self.tagList.setMaximumSize(QtCore.QSize(176, 16777215))
        self.tagList.setObjectName("tagList")
        self.gridLayout.addWidget(self.tagList, 1, 2, 1, 1)
        self.label = QtGui.QLabel(ThumbnailArea)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)

        self.retranslateUi(ThumbnailArea)
        QtCore.QMetaObject.connectSlotsByName(ThumbnailArea)

    def retranslateUi(self, ThumbnailArea):
        self.nextPageButton.setText(kdecore.i18n("Add Page"))
        self.label.setText(kdecore.i18n("Similar tags:"))

from PyKDE4.kdeui import KPushButton, KTabWidget

if __name__ == '__main__':
    import sys
    global app
    class MainWin(kdeui.KMainWindow, Ui_ThumbnailArea):
        def __init__ (self, *args):
            kdeui.KMainWindow.__init__ (self)
            rootWidget = QtGui.QWidget(self)
            self.setupUi(rootWidget)
            self.resize(640, 480)
            self.setCentralWidget(rootWidget)
    
    appName     = "default"
    catalog     = ""
    programName = kdecore.ki18n("default")
    version     = "1.0"
    description = kdecore.ki18n("Default Example")
    license     = kdecore.KAboutData.License_GPL
    copyright   = kdecore.ki18n("unknown")
    text        = kdecore.ki18n("none")
    homePage    = ""
    bugEmail    = "email"

    aboutData   = kdecore.KAboutData(appName, catalog, programName, version, description,
                              license, copyright, text, homePage, bugEmail)
    kdecore.KCmdLineArgs.init(sys.argv, aboutData)
    
    app = kdeui.KApplication()
    mainWindow = MainWin(None, "main window")
    mainWindow.show()
    app.connect (app, QtCore.SIGNAL ("lastWindowClosed ()"), app.quit)
    app.exec_ ()
