#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/danboorupage.ui on Sat Oct 24 15:12:50 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_DanbooruPage(object):
    def setupUi(self, DanbooruPage):
        DanbooruPage.setObjectName("DanbooruPage")
        DanbooruPage.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(DanbooruPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kcfg_danbooruUrls = KEditListBox(DanbooruPage)
        self.kcfg_danbooruUrls.setFlat(True)
        self.kcfg_danbooruUrls.setCheckable(False)
        self.kcfg_danbooruUrls.setButtons(KEditListBox.Button(KEditListBox.Add|KEditListBox.Remove))
        self.kcfg_danbooruUrls.setObjectName("kcfg_danbooruUrls")
        self.verticalLayout.addWidget(self.kcfg_danbooruUrls)

        self.retranslateUi(DanbooruPage)
        QtCore.QMetaObject.connectSlotsByName(DanbooruPage)

    def retranslateUi(self, DanbooruPage):
        pass

from PyKDE4.kdeui import KEditListBox
